name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    strategy:
      matrix:
        browser: [ chrome, firefox, edge ]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.14.2'
        cache: 'npm'
    - run: npm ci
    
    - name: Cypress run tests in ${{ matrix.browser }}
      uses: cypress-io/github-action@v4
      with:
        browser: ${{ matrix.browser }}
    - run: echo ">>>>>>" ${{ matrix.browser }}
    - run: npm test
